version: "3.6"
services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
      - "VAULT_ADDR=http://127.0.0.1:8200"
      - "VAULT_DEV_ROOT_TOKEN_ID=just-for-dev"
    ports:
      - "8201:8201"
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
        # - ./file:/vault/file:rw
        - ./config:/vault/config:rw
